modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="forest"
version="1.3.0.230718"
displayName="Forest X Reborn"
credits="Created by MagicalAlexey with the support of 7ZLBeka, maxD, Samuelchik"
displayURL="https://power-umc.ru/minecraft-java-edition/mods/5-forest-x-reborn.html"
logoFile="logo.png"
authors="UMC"
description="The revival of the legendary Forest X Second Edition addon, but only for Minecraft Java Edition.  "

[[dependencies.forest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.forest]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.forest]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.forest]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

